# Generated by Django 3.1.3 on 2020-12-15 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kartingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='mdl_search',
        ),
        migrations.AddField(
            model_name='search',
            name='Search',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='mdl_contact',
            field=models.IntegerField(unique=True),
        ),
    ]
