# Generated by Django 3.1.3 on 2020-12-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartingapp', '0002_auto_20201216_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='Search',
            new_name='mdl_search',
        ),
    ]
