# Generated by Django 3.1.3 on 2020-12-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartingapp', '0003_auto_20201216_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='mdl_search',
            field=models.CharField(max_length=300),
        ),
    ]
